#pragma once
#include <stdint.h>
#include <math.h>
#include "esp_log.h"
#include "esp_heap_caps.h"
#include "config.h"

// ─────────────────────────────────────────────────────────────────────────────
//  model_runner.h  –  TFLite Micro inference (esp-tflite-micro component)
//
//  Include path comes from the esp-tflite-micro component, which is resolved
//  by the IDF Component Manager (idf_component.yml).
//  Unlike the Arduino library, this build includes ALL ops and is kept in sync
//  with upstream tflite-micro — no missing-op surprises.
//
//  INPUT FORMAT:
//    input 0 – signal  (1, 1, 1500)  float32
//    input 1 – mask    (1, 1, 1500)  float32
//    input 2 – demo    (1, 8)        float32
//              [age, sex, height, weight, bmi, actual_hr, preop_htn, preop_dm]
//    output 0 – glucose (1,)          float32  (mmol/L)
// ─────────────────────────────────────────────────────────────────────────────

// esp-tflite-micro headers (resolved via IDF component system)
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_log.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "model_data.h"   // generated by xxd -i best_model.tflite

static const char* TAG_MODEL = "MODEL";

// ── Op resolver ──────────────────────────────────────────────────────────────
// MicroMutableOpResolver is preferred over AllOpsResolver in production:
// it only links the ops you actually use, saving ~200 KB of flash.
// List here exactly the ops your converted model needs.
// Run `python tools/list_tflite_ops.py best_model.tflite` to get the list.
using OpsResolver = tflite::MicroMutableOpResolver<20>;

static OpsResolver* g_resolver = nullptr;

static bool build_resolver() {
    g_resolver = new OpsResolver();
    if (g_resolver->AddConv2D()             != kTfLiteOk) return false;
    if (g_resolver->AddRelu()               != kTfLiteOk) return false;
    if (g_resolver->AddResizeNearestNeighbor() != kTfLiteOk) return false;
    if (g_resolver->AddMul()               != kTfLiteOk) return false;
    if (g_resolver->AddMean()              != kTfLiteOk) return false;  // GlobalAvgPool → MEAN
    if (g_resolver->AddSqueeze()           != kTfLiteOk) return false;
    if (g_resolver->AddConcatenation()     != kTfLiteOk) return false;
    if (g_resolver->AddFullyConnected()    != kTfLiteOk) return false;
    if (g_resolver->AddReshape()           != kTfLiteOk) return false;
    if (g_resolver->AddQuantize()          != kTfLiteOk) return false;  // safety: float model may still emit this
    if (g_resolver->AddAdd()               != kTfLiteOk) return false;
    if (g_resolver->AddAveragePool2D()     != kTfLiteOk) return false;
    if (g_resolver->AddSum()               != kTfLiteOk) return false;
    if (g_resolver->AddSelectV2()          != kTfLiteOk) return false;
    if (g_resolver->AddPad()               != kTfLiteOk) return false;
    if (g_resolver->AddDepthwiseConv2D()   != kTfLiteOk) return false;
    if (g_resolver->AddTranspose()         != kTfLiteOk) return false;
    if (g_resolver->AddGatherNd()          != kTfLiteOk) return false;
    return true;
}

// ── Tensor arena ─────────────────────────────────────────────────────────────
// Allocated in PSRAM via heap_caps_malloc — requires CONFIG_SPIRAM_USE_MALLOC=y
static uint8_t* g_tensor_arena = nullptr;

// ── Interpreter state ─────────────────────────────────────────────────────────
static const tflite::Model*      g_model       = nullptr;
static tflite::MicroInterpreter* g_interpreter = nullptr;
static TfLiteTensor*             g_in_signal   = nullptr;
static TfLiteTensor*             g_in_mask     = nullptr;
static TfLiteTensor*             g_in_demo     = nullptr;
static TfLiteTensor*             g_output      = nullptr;

bool model_init() {
    // ── Allocate tensor arena in PSRAM ───────────────────────────────────────
    g_tensor_arena = (uint8_t*)heap_caps_malloc(
        TENSOR_ARENA_SIZE, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (!g_tensor_arena) {
        ESP_LOGE(TAG_MODEL, "PSRAM alloc failed (%u bytes). "
                 "Check sdkconfig: CONFIG_SPIRAM_USE_MALLOC=y", TENSOR_ARENA_SIZE);
        return false;
    }
    ESP_LOGI(TAG_MODEL, "Arena: %u KB in PSRAM", TENSOR_ARENA_SIZE / 1024);

    // ── Load model flatbuffer ─────────────────────────────────────────────────
    g_model = tflite::GetModel(g_model_data);
    if (g_model->version() != TFLITE_SCHEMA_VERSION) {
        ESP_LOGE(TAG_MODEL, "Schema mismatch: model=%u runtime=%u",
                 (unsigned)g_model->version(), (unsigned)TFLITE_SCHEMA_VERSION);
        ESP_LOGE(TAG_MODEL, "Reconvert the model with a matching TFLite version");
        return false;
    }

    // ── Build op resolver ─────────────────────────────────────────────────────
    if (!build_resolver()) {
        ESP_LOGE(TAG_MODEL, "Op resolver setup failed");
        return false;
    }

    // ── Build interpreter ─────────────────────────────────────────────────────
    static tflite::MicroInterpreter static_interpreter(
        g_model, *g_resolver, g_tensor_arena, TENSOR_ARENA_SIZE);
    g_interpreter = &static_interpreter;

    // ── Allocate tensors ──────────────────────────────────────────────────────
    TfLiteStatus status = g_interpreter->AllocateTensors();
    if (status != kTfLiteOk) {
        ESP_LOGE(TAG_MODEL, "AllocateTensors failed");
        ESP_LOGE(TAG_MODEL, "  Possible causes:");
        ESP_LOGE(TAG_MODEL, "  1. Missing op — run tools/list_tflite_ops.py and add to build_resolver()");
        ESP_LOGE(TAG_MODEL, "  2. Arena too small — increase TENSOR_ARENA_SIZE in config.h");
        ESP_LOGE(TAG_MODEL, "  3. Schema version mismatch (see above)");
        return false;
    }

    // ── Log input shapes ──────────────────────────────────────────────────────
    int n = g_interpreter->inputs_size();
    ESP_LOGI(TAG_MODEL, "Loaded OK. Inputs: %d. Arena used: %u bytes",
             n, (unsigned)g_interpreter->arena_used_bytes());
    for (int i = 0; i < n; i++) {
        TfLiteTensor* t = g_interpreter->input(i);
        ESP_LOGI(TAG_MODEL, "  input[%d]: dims=%d", i, t->dims->size);
    }

    // ── Assign tensor pointers ────────────────────────────────────────────────
    // Indices 0,1,2 must match the export order — verify from log above.
    g_in_signal = g_interpreter->input(0);
    g_in_mask   = g_interpreter->input(1);
    g_in_demo   = g_interpreter->input(2);
    g_output    = g_interpreter->output(0);

    return true;
}

float model_infer(const float* signal_1500,
                  const float* mask_1500,
                  const float* demo) {
    memcpy(g_in_signal->data.f, signal_1500, SIGNAL_LEN    * sizeof(float));
    memcpy(g_in_mask->data.f,   mask_1500,   SIGNAL_LEN    * sizeof(float));
    memcpy(g_in_demo->data.f,   demo,        NUM_DEMO_FEAT * sizeof(float));

    if (g_interpreter->Invoke() != kTfLiteOk) {
        ESP_LOGE(TAG_MODEL, "Invoke failed");
        return NAN;
    }
    return g_output->data.f[0];
}
